apiVersion: v2
name: infra
description: Infrastructure Helm chart for OpenShift app modernization
type: application
version: 0.2.0
appVersion: "1.16.0"

dependencies:
  - name: openbao
    version: 0.28.3
    repository: https://openbao.github.io/openbao-helm
