kind: Namespace
apiVersion: v1
metadata:
  name: openbao
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-eso-auth
  namespace: openbao
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openbao
  namespace: openbao
spec:
  to:
    kind: Service
    name: openbao
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
