apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/shirodkar/app-mod-gitops.git'
    targetRevision: HEAD
    path: manifests/helm/infra
    helm: {}
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true
  ignoreDifferences:
    - kind: ServiceAccount
      jsonPointers:
        - /imagePullSecrets